### ISSUE TITLE
Grouped by undefined in tasks

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/fusion-project-portal#162]
![image](https://user-images.githubusercontent.com/89254170/234481464-dff54ff5-8219-47c5-84e2-9d672e3414a8.png)

**Comment by Noggling** [comment]
@MagnusGjosund Det er enkelte verdier vi grupperer på som kan være undefined vi må finne en bedre måte og vise det på eller fjerne grupperings muligheten.

**Comment by Noggling** [comment]
fiks også denne i samme slengen 

act_devtools_backend.js:2655 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Tasks`. See https://reactjs.org/link/warning-keys for more information.
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at Tasks (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/portal-ui/src/lib/task/work-assigned/Tasks.tsx:82:3)
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at CardContent2 (http://localhost:3000/node_modules/.vite/deps/@equinor_eds-core-react.js?v=d28ad9bd:3139:23)
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at Paper2 (http://localhost:3000/node_modules/.vite/deps/@equinor_eds-core-react.js?v=d28ad9bd:2949:27)
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at Card2 (http://localhost:3000/node_modules/.vite/deps/@equinor_eds-core-react.js?v=d28ad9bd:2969:24)
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at WorkAssigned
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at main
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at ProjectPage (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/portal-pages/src/pages/project-page/ProjectPage.tsx:33:7)
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:427:5)
    at RenderErrorBoundary (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:390:5)
    at Outlet (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:730:26)
    at MenuProvider (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/portal-core/src/providers/menu/MenuProvider.tsx:28:3)
    at ViewProvider (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/portal-core/src/providers/current-view/CurrentViewContext.tsx:32:3)
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at NotificationService (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/service-message/components/NotificationService.tsx:40:3)
    at ServiceMessageProvider (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/service-message/provider/ServiceMessageProvider.tsx:85:3)
    at div
    at O2 (http://localhost:3000/node_modules/.vite/deps/chunk-IHHTVH4O.js?v=c28fc8d4:1172:6)
    at fwc-theme
    at ThemeProvider (http://localhost:3000/node_modules/.vite/deps/chunk-DMQWDTKK.js?v=c28fc8d4:3223:24)
    at ThemeProvider2 (http://localhost:3000/node_modules/.vite/deps/chunk-DMQWDTKK.js?v=c28fc8d4:4509:11)
    at EdsProvider2 (http://localhost:3000/node_modules/.vite/deps/@equinor_eds-core-react.js?v=d28ad9bd:1289:23)
    at StyleProvider (http://localhost:3000/@fs/Users/christopher.hove/git/fusion-project-portal/client/packages/portal-ui/src/lib/style-provider/styleProvider.tsx:25:3)
    at PortalFrame
    at RenderedRoute (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:427:5)
    at RenderErrorBoundary (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:390:5)
    at Routes (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:790:5)
    at Router (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:737:15)
    at RouterProvider (http://localhost:3000/node_modules/.vite/deps/react-router-dom.js?v=7c751a1f:631:5)
    at PortalRouter (http://localhost:3000/src/components/portal-router/PortalRouter.tsx:157:7)
    at default (http://localhost:3000/node_modules/.vite/deps/@equinor_fusion-framework-react.js?v=50447bab:2045:17)
    at Suspense
    at Framework (http://localhost:3000/node_modules/.vite/deps/@equinor_fusion-framework-react.js?v=50447bab:2053:103)
    at QueryClientProvider2 (http://localhost:3000/node_modules/.vite/deps/react-query.js?v=c7cff914:2641:21)
o
